#!/bin/sh

# NOTE: becomes .tmp_update/updater

INFO=`cat /proc/cpuinfo 2> /dev/null`
case $INFO in
*"SStar"*)
	PLATFORM="miyoomini"
	;;
*"0xd05"*)
	PLATFORM="my355" # Miyoo Flip
	;;
esac

exec "/mnt/SDCARD/.tmp_update/$PLATFORM.sh" # &> /mnt/SDCARD/boot.txt
